# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fort < Formula
  desc "Deterministic agent orchestration — route, run, and gate agent CLIs natively"
  homepage "https://github.com/tobsai/fort"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tobsai/fort/releases/download/v0.7.0/fort_0.7.0_darwin_amd64.tar.gz"
      sha256 "a01af8ad3cff53af891717b3a50dc00923b39a2d72fd00ba53590aa74a6c6c08"

      define_method(:install) do
        bin.install "fort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tobsai/fort/releases/download/v0.7.0/fort_0.7.0_darwin_arm64.tar.gz"
      sha256 "501d79b7c3593485b3e4ac97c47bb215aab2f0ddb70d279e580fac710140708a"

      define_method(:install) do
        bin.install "fort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobsai/fort/releases/download/v0.7.0/fort_0.7.0_linux_amd64.tar.gz"
      sha256 "442a5a2c3521a11a646273038ea838a9b16e6d1331d3a0de03f5dae34dc5d8de"
      define_method(:install) do
        bin.install "fort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobsai/fort/releases/download/v0.7.0/fort_0.7.0_linux_arm64.tar.gz"
      sha256 "df5dcb552ab1dad94d1b7848c7c8745defcffc6e4ff8673d5b4262712a3fe51d"
      define_method(:install) do
        bin.install "fort"
      end
    end
  end

  test do
    system "#{bin}/fort", "version"
  end
end
