# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fort < Formula
  desc "Deterministic agent orchestration — route, run, and gate agent CLIs natively"
  homepage "https://github.com/tobsai/fort"
  version "0.10.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tobsai/fort/releases/download/v0.10.3/fort_0.10.3_darwin_amd64.tar.gz"
      sha256 "5967882fb967b8cc590bfe6b5f8697034fc6122c51bc9118a68028bb8c8580c5"

      define_method(:install) do
        bin.install "fort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tobsai/fort/releases/download/v0.10.3/fort_0.10.3_darwin_arm64.tar.gz"
      sha256 "e70734286e594aec2f108e84d1179281b7d1aeb71a14a5f54c666e4e56e11d17"

      define_method(:install) do
        bin.install "fort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobsai/fort/releases/download/v0.10.3/fort_0.10.3_linux_amd64.tar.gz"
      sha256 "26bf49018017a69a7fae2c01b653a97fc4ba9643ed2eef14c37c0cb5313a544f"
      define_method(:install) do
        bin.install "fort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobsai/fort/releases/download/v0.10.3/fort_0.10.3_linux_arm64.tar.gz"
      sha256 "24052f59fd3cd29e1ead478d0f576f1282fb2f18b50c68ea9eca180605a7dd92"
      define_method(:install) do
        bin.install "fort"
      end
    end
  end

  test do
    system "#{bin}/fort", "version"
  end
end
