# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fort < Formula
  desc "Deterministic agent orchestration — route, run, and gate agent CLIs natively"
  homepage "https://github.com/tobsai/fort"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tobsai/fort/releases/download/v0.13.0/fort_0.13.0_darwin_amd64.tar.gz"
      sha256 "1224b1470d5ccc22995b0e54ac43227fd07f4d54c31e8af22c560daabb5745f0"

      define_method(:install) do
        bin.install "fort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tobsai/fort/releases/download/v0.13.0/fort_0.13.0_darwin_arm64.tar.gz"
      sha256 "d1f65c18b46d1fcb94734ab525837dfbf5923b0b80f871bcd2653c8f96d94cc4"

      define_method(:install) do
        bin.install "fort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobsai/fort/releases/download/v0.13.0/fort_0.13.0_linux_amd64.tar.gz"
      sha256 "a1a6427cf320ad13b54daf5a7bc3be51a4011c6110096469059b7c0505f8c6ee"
      define_method(:install) do
        bin.install "fort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobsai/fort/releases/download/v0.13.0/fort_0.13.0_linux_arm64.tar.gz"
      sha256 "54dfaa8c750c84ea5ca21af999db1cf2b67ac99a39f1aa64e07147c30d423c12"
      define_method(:install) do
        bin.install "fort"
      end
    end
  end

  test do
    system "#{bin}/fort", "version"
  end
end
